#!/bin/bash
source "$HOME/smart-git/lib/color"
isTermux() {
  if [[ -f /data/data/com.termux/files/usr/bin/bash ]]; then
    return 0  # Termux
  else
    return 1  # Not Termux
  fi
}

smartGitInstall() {
  if [[ ! -d "$HOME/smart-git" ]]; then
    red "Error: smart-git folder not found in the home directory"
    return 1
  fi

  if [[ ! -x "$HOME/smart-git/bin/sgit" ]]; then
    chmod +x "$HOME/smart-git/bin/sgit"
    if [[ $? -ne 0 ]]; then
      red "Error: Failed to make sgit executable"
      return 1
    fi
  fi

  if isTermux; then
    if [[ ! -L "$HOME/bin/sgit" ]]; then
      ln -s "$HOME/smart-git/bin/sgit" "$HOME/bin/sgit"
      green "Symlink for sgit created in $HOME/bin"
    else
    yellow "Symlink for sgit already exists in $HOME/bin"
    exit 1
    fi
  else
    if [[ ! -L "/usr/local/bin/sgit" ]]; then
      sudo ln -s "$HOME/smart-git/bin/sgit" /usr/local/bin/sgit
      green "Symlink for sgit created in /usr/local/bin"
    else
      yellow "Symlink for sgit already exists in /usr/local/bin"
      exit
    fi
  fi

  if ! grep -q 'alias sgit=' ~/.bashrc; then
    echo 'alias sgit="$HOME/smart-git/bin/sgit"' >> ~/.bashrc
    green "Alias for sgit added to .bashrc"
  else
    yellow "Alias for sgit already exists in .bashrc"
    exit 0
  fi

  source ~/.bashrc
  if [[ $? -eq 0 ]]; then
    green "smart-git installed successfully and alias applied"
  else
    red "Error: Failed to source ~/.bashrc"
  fi
}

smartGitInstall
